name: GitHub Profile Trophy

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate Trophy
        uses: ryo-ma/github-profile-trophy@v1
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER: VirenPassi
          theme: tokyonight
          no-bg: "false"
          no-frame: "true"
          column: "8"
          margin-w: "15"
          output_action: "save"
          file_output: "assets/trophies.svg"
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "update-trophies"
